
on:
  push:
    branches: [master]
name: Deploy website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Build Nuxt
        run: |
          npm install
          npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: /
          server-dir: repositories/portfolio/

#  cloudlinux-selector start --json --interpreter nodejs --user uqcb4840 --app-root /home/uqcb4840/florianguigue/findmyshow
#  cloudlinux-selector stop --json --interpreter nodejs --user uqcb4840 --app-root /home/uqcb4840/florianguigue/findmyshow
